name: 🐞 Report an issue
description: Report an issue
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only!
        If you want to request a new feature or an enhancement, please use the other issues types.

        This project is maintained in our spare time. Please be patient and respectful.
        It's not related to Ecovacs or Deebot and we don't get any support from them.
        As all is reverse engineered it might take some time to fix issues.
        Due to the fact that this is a hobby project, we can't guarantee that all issues will be fixed.
        Unfortunately some people think we are paid to do this and get angry if things don't work as they expect.
        As result of this, we decided that this project is in a contribution only mode.
        This means, if you want something to be fixed, you have to provide a fix yourself, wait for someone else to fix it or pay someone to do it.
        It's not allowed to ping any members of the project to ask for help or to fix your issue.
        If you do so, your issue will be closed without further notice.
  - type: checkboxes
    attributes:
      label: Checks
      options:
        - label: I have read the above text and I'm aware of the situation
          required: true
        - label: I have searched the existing issues and no issue is describing my issue
          required: true
        - label: I'm not creating an issue to add support for a new device/model.
          required: true
        - label: I have installed the latest version
          required: true

  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing here to communicate to the
        maintainers. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.

  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    id: device
    validations:
      required: true
    attributes:
      label: On which deebot device (vacuum) you have the issue?
      placeholder: Deebot Ozmo 950
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: Which version of the deebot-client are you using?
      placeholder: X.X.X
  - type: markdown
    attributes:
      value: |
        # Configuration
  - type: input
    id: country
    validations:
      required: true
    attributes:
      label: Country
      placeholder: it
      description: >
        Which country did you input during the setup of the integration?
  - type: input
    id: continent
    validations:
      required: true
    attributes:
      label: Continent
      placeholder: eu
      description: >
        Which continent did you input during the setup of the integration?

  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    attributes:
      label: Anything in the logs that might be useful for us?
      description: >
        For example, error message, or stack traces.

        Please refer to the [documentation](https://deebot.readthedocs.io/integrations/home-assistant/issues/).
      render: txt
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
