blank_issues_enabled: false
contact_links:
  - name: "Home Assistant Ecovacs documentation"
    url: https://www.home-assistant.io/integrations/ecovacs
    about: Documentation how to use the Ecovacs integration in Home Assistant
