name: 💡 Suggest a feature/idea
description: Suggest a feature/idea
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting features/ideas only!
        For others, please use the other issues types.

        This project is maintained in our spare time. Please be patient and respectful.
        It's not related to Ecovacs or Deebot and we don't get any support from them.
        As all is reverse engineered it might take some time to add new features.
        Due to the fact that this is a hobby project, we can't guarantee that all features will be added.
        Unfortunately some people think we are paid to do this and get angry if things don't work as they expect.
        As result of this, we decided that this project is in a contribution only mode.
        This means, if you want something to be supported/added, you have to provide a fix yourself, wait for someone else to fix it or pay someone to do it.
        It's not allowed to ping any members of the project to ask for help.
        If you do so, your issue will be closed without further notice.
  - type: checkboxes
    attributes:
      label: Checks
      options:
        - label: I have read the above text and I'm aware of the situation
          required: true
        - label: I have searched the existing issues and no issue is describing my issue
          required: true
        - label: I have installed the latest version
          required: true

  - type: textarea
    validations:
      required: true
    attributes:
      label: The feature you want to suggest
      description: >-
        Describe the feature you want to suggest here to communicate to the
        maintainers. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the feature is.
