from __future__ import annotations

import base64
import lzma
from typing import Any

import orjson

FULL_SNAPSHOT = [["1", "1", "1;1;100;0,0;100,0", "1;2;0;550,-2400;2(2)"]]
PATCH_ADD = [["1", "2", "1;1;101;0,100;100,100"]]
PATCH_REPLACE = [["1", "2", "1;1;100;0,0;150,0"]]
PATCH_DELETE = [["1", "2", "1;1;100"]]
OUTER_TWO_UPDATES = [
    ["1", "1", "1;1;100;0,0;100,0"],
    ["1", "2", "1;1;100;0,0;150,0"],
]
UNKNOWN_PROTOCOL = [["2", "1", "1;1;100;0,0;100,0"]]
UNKNOWN_UPDATE_TYPE = [["1", "9", "1;1;100;0,0;100,0"]]
COMPLETION_LIKE_RESIDUAL = [
    [
        "1",
        "1",
        "1;1;311;900,349;1100,349",
        "1;1;312;800,449;1150,449",
        "1;1;322;1150,1449;1600,1449",
        "1;1;324;-650,1649;350,1649;1600,1649;1700,1649",
        "1;2;0;550,-2400;2(4)",
    ],
    ["1", "2", "1;1;311"],
]

# Literal sanitized production payloads from p2-16b:
# .goat-map-phase2/p2-16b-onmaptrack-ui-validation-sentrum/run-20260830-131021
# sequences 59/60 (initial full snapshot with key-only records) and 180 (patch
# with key-only delete). These are intentionally not generated by trimmed_lzma().
REAL_P2_16B_INITIAL_FULL_WITH_KEY_ONLY = [
    {
        "body": {
            "data": {
                "mid": "0",
                "totalWidth": 0,
                "totalHeight": 0,
                "resolution": 0,
                "batid": "ffnalc",
                "serial": "2",
                "index": "0",
                "info": "XQAABADLFAAAAC2WwEIAXhR4HiMyu/KbCZVM7BKG/QGCVt5FhfdpAc8ZecmTAcA3OYsGVRBSjZawnnLxjMCBmMiIeWOmYQbrLmf7utl4bkC1O8dUoaJBDofhHVenoEOc9diKWEZPA1deXHY8KQUtQQEM7CEUAZHaRTiq6WCaqCbMxNDnS+TiI3Y2x1FDBeexuG7fE2X3+J6WV5+nlyS3N6Djej0bV71q7XQlUFQxsKZZaKRSqoTmBRxllMTgJ0G23S0Z7mPyAkc63Yr3euJrtAGWROaXNHokP5Siln0BQzDAOLzLyUttuPu8lT2UAgIR7g8CA/SOKk8eigjOxLr8FC/dz2qTMiyAHMMSPCPqAywIAetPnp9uhkozJsfdvY2C77dvsBoHCiDfaadsVTWWEwWpNi5jlvLaN8vZLJ+Eqi5n0H89StsH4CL8qJU4JBiIYupYZWd0wMjQ5u/0gtD84AjgW+T8kS9MdsfMPcyIuaVPimRVC7nUmdSVkEwN3U9FYWrul4oNbE2CiJBAN29ZpQXulXb2F3RCtRsSOCiYcxd8oBsaAf6pTEOOW1xPUaXnRmigeuQkGc6i/8q1QrYMVjaKNHng4IcEor9xhUW6keSWlDONfx87t1nvATM2im26gpWKCFT8vhRQ8Urkx+BPZVwuBoM5VId4VVWWsnWghSZ7NrSx8dLwUVeJUJQvYzbiTqq8hxGjHpE0QQD8AfpJVEW8VGCFQkvgUZOhV3psAigfvo6UNCmqaIBQOQt37nidCAYieMxi6b6FA6tdN2Wvh0l4F+rWQaGtqY3JMAZ/Nj4nWlEK2SIoiIdxpELV8aEfYgHW0FVPZ/4V/fB4/a9D7cXUZRGAdeQOxJh2N0PERoVMAed+2/WEhvyZWngEG7fjpmEQatW8/nylcqcRlazrv4uXj8YGJxAcb9YVWlISz+Fng81G1bTjOiw+zj24bFpqQaHskmO/SApQKv0peGKWxsPTmkDo0NQFE72RRBDemzC4k1JSF8kxqzoKXbEFYY2q",
                "infoSize": 5323,
            }
        }
    },
    {
        "body": {
            "data": {
                "mid": "0",
                "totalWidth": 0,
                "totalHeight": 0,
                "resolution": 0,
                "batid": "ffnalc",
                "serial": "2",
                "index": "1",
                "info": "T2c8UgqO83FOnzskLethkr7Su57Xf4Eg9zASzDb5AVlo2lYvd3nOS7qfo7zD0hnufV18QRTXn9MBr0BLMoI2V5T8Nmy/2/viA4nnHnizWuDTA7WPx9Cu8tjicvqNX5A2NltIfBKwOMnvVfo84781QWxtUDxl1r11yvpofILXX9hhMjMieTOXOC9adps+r6iFnHUXu6NmAToq+eBiNBJ6QXGvuNb0NUKkrdwa92yjso8sarWTbKyfyhIwaQ4k/cV+3Ls2eONjKSMHk+oUReekX3ue+aA8HVJqpGCN9xS81jQe+n53u8Sp8dVbQ252u/SC5UdnVKChXkq1PK6Ko9CWvsKJIGP9wQXYiP3HGsd0eq/t6KpcxPszcLDCAFMoURhnR5NMjuYcjirtIMfmjknZqQ2dWRuprLUbX8qXjAHz9ZI5Pm5H+sTfd7QzWO4BkSOsnvGArnOJCgEpQT27vuM5yUYxbgREszmzSAGFHB7m0vh5gxpwAW7dN2dFPfY0/i8jKimvySQ7dRDvcCQ4AA==",
                "infoSize": 5323,
            }
        }
    },
]

REAL_P2_16B_PATCH_KEY_ONLY_DELETE = [
    {
        "body": {
            "data": {
                "mid": "0",
                "totalWidth": 0,
                "totalHeight": 0,
                "resolution": 0,
                "batid": "dehlgp",
                "serial": "1",
                "index": "0",
                "info": "XQAABABGAAAAAC2WwEIAXhHX7tffCWokOBz8yLYFqm7yyOt/yYdrywRa82c8j8WXAHWrrrmHAA==",
                "infoSize": 70,
            }
        }
    },
]


def trimmed_lzma(value: Any) -> tuple[str, int]:
    decoded = orjson.dumps(value)
    compressed = bytearray(
        lzma.compress(
            decoded,
            format=lzma.FORMAT_ALONE,
            filters=[
                {
                    "id": lzma.FILTER_LZMA1,
                    "dict_size": 1 << 18,
                    "lc": 3,
                    "lp": 0,
                    "pb": 2,
                }
            ],
        )
    )
    compressed[5:13] = len(decoded).to_bytes(8, "little")
    trimmed = compressed[:9] + compressed[13:]
    return base64.b64encode(trimmed).decode(), len(decoded)


def chunked_messages(
    document: Any,
    *,
    batid: str,
    mid: str = "0",
    chunks: int = 1,
) -> list[dict[str, Any]]:
    info, info_size = trimmed_lzma(document)
    raw = base64.b64decode(info, validate=True)
    chunk_size = max(1, (len(raw) + chunks - 1) // chunks)
    parts = [
        raw[index : index + chunk_size] for index in range(0, len(raw), chunk_size)
    ]
    return [
        {
            "body": {
                "data": {
                    "mid": mid,
                    "batid": batid,
                    "serial": str(len(parts)),
                    "index": str(index),
                    "infoSize": info_size,
                    "info": base64.b64encode(part).decode(),
                }
            }
        }
        for index, part in enumerate(parts)
    ]
