ARG PYTHON_VERSION
FROM python:${PYTHON_VERSION}-alpine

ENV \
    UV_SYSTEM_PYTHON=true

ENTRYPOINT [ "/entrypoint.sh" ]
SHELL ["/bin/sh", "-o", "pipefail", "-c"]

COPY ci/entrypoint.sh /entrypoint.sh

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

COPY requirements.txt /requirements.txt

RUN \
    uv pip install -r /requirements.txt